spring.application.name=conduit

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/conduit
spring.datasource.username=conduit
spring.datasource.password=conduit

# JPA
spring.jpa.hibernate.ddl-auto=validate

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# Redis
#spring.data.redis.host=localhost
#spring.data.redis.port=6379

# Actuator
management.endpoints.web.exposure.include=health,metrics,prometheus