package com.example.conduit.enums;

public enum EventType {
    EXECUTION_STARTED,
    STATE_ENTERED,
    STATE_EXITED,
    TASK_SCHEDULED,
    TASK_STARTED,
    TASK_SUCCEEDED,
    TASK_FAILED,
    TASK_TIMED_OUT,
    RETRY_SCHEDULED,
    RETRY_DUE,
    WAIT_STARTED,
    WAIT_COMPLETED,
    CHOICE_EVALUATED,
    PARALLEL_STARTED,
    PARALLEL_BRANCH_FAILED,
    PARALLEL_SUCCEEDED,
    MAP_STARTED,
    MAP_ITERATION_FAILED,
    MAP_SUCCEEDED,
    EXECUTION_SUCCEEDED,
    EXECUTION_FAILED,
    EXECUTION_ABORTED,
    EXECUTION_TIMED_OUT
}
